apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 99app
                    operator: In
                    values:
                      - g3statefulapp
      containers:
        - name: varnish
          image: nexus.99acres.com
          readinessProbe:
            tcpSocket:
              port: 6081
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            tcpSocket:
              port: 6081
            initialDelaySeconds: 15
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: BRANCH
              value: "sanity"
            - name: DISK_SIZE
              value: "2G"

          volumeMounts:
            - name: varnish-logs
              mountPath: /data/logs
            - name: varnish-data
              mountPath: /var/lib/varnish

      volumes:
        - name: varnish-logs
          hostPath:
            path: /data/ws-logs/varnish/

        - name: varnish-data
          hostPath:
            path: /data/varnish/

      imagePullSecrets:
        - name : nexuscreds
---

apiVersion: v1
kind: Service
metadata:
  name: varnish-nodeport
  labels:
    app: varnish
spec:
  type: NodePort
  ports:
    - targetPort: 6081
      port: 8080
      nodePort: 31289
    - targetPort: 9131
      port: 8085
      nodePort: 31290
  selector:
    app: varnish
