apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 99app
                    operator: In
                    values:
                      - g3statefulapp # Replace with the name of the node you want to deploy on
      containers:
        - name: varnish
          image: hackerad/pesi-plus:1.0
          imagePullSecrets:
            - name: nexuscreds
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 6081
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 6081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
          env:
            - name: BRANCH
              value: "sanity"
            - name: DISK_SIZE
              value: "2G"

          volumeMounts:
            - name: varnish-logs
              mountPath: /data/logs
            - name: varnish-data
              mountPath: /var/lib/varnish

      volumes:
        - name: varnish-logs
          hostPath:
            path: /data/ws-logs/varnish/

        - name: varnish-data
          hostPath:
            path: /data/varnish/
---

apiVersion: v1
kind: Service
metadata:
  name: varnish-nodeport
  labels:
    app: varnish
spec:
  type: NodePort
  ports:
    - targetPort: 6081
      port: 8080
      nodePort: 31289
  selector:
    app: varnish
